# Generated by Django 6.0 on 2025-12-16 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 수정일자')),
                ('created_by', models.CharField(default='admin', verbose_name='등록자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 유무')),
                ('camera_key', models.CharField(db_index=True, max_length=128)),
                ('stream_path', models.CharField(max_length=128, unique=True)),
                ('original_rtsp', models.CharField(max_length=1024)),
                ('stream_type', models.CharField(choices=[('rtsp', 'RTSP'), ('hls', 'HLS'), ('webrtc', 'WebRTC')], max_length=16)),
                ('source_on_demand', models.BooleanField(default=False)),
                ('token_auth_enabled', models.BooleanField(default=True)),
                ('last_issued_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_issued_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='업체')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media stream',
                'db_table': 'media_stream',
                'indexes': [models.Index(fields=['company', 'stream_type'], name='media_strea_company_ddde2e_idx')],
                'unique_together': {('company', 'camera_key')},
            },
        ),
    ]
