# Generated by Django 6.0 on 2025-12-10 12:51

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 수정일자')),
                ('created_by', models.CharField(default='admin', verbose_name='등록자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 유무')),
                ('name', models.CharField(default='', max_length=256, verbose_name='그룹명')),
            ],
            options={
                'verbose_name': '권한 그룹',
                'db_table': 'permission_group',
            },
        ),
        migrations.CreateModel(
            name='MenuPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 수정일자')),
                ('created_by', models.CharField(default='admin', verbose_name='등록자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 유무')),
                ('name', models.CharField(default='', max_length=256, verbose_name='메뉴명')),
                ('permissions', models.BooleanField(default=True, verbose_name='권한')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='masterdata.menupermissions')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.permissiongroup', verbose_name='권한 그룹')),
            ],
            options={
                'verbose_name': '메뉴 권한',
                'db_table': 'menu_permissions',
            },
        ),
    ]
