# Generated by Django 6.0 on 2025-12-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 수정일자')),
                ('created_by', models.CharField(default='admin', verbose_name='등록자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 유무')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='회사명')),
                ('representative', models.CharField(blank=True, max_length=256, null=True, verbose_name='대표자')),
                ('registration_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='사업자등록번호')),
                ('business_item', models.CharField(blank=True, max_length=256, null=True, verbose_name='업종')),
                ('business_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='업태')),
                ('business_start_dt', models.DateTimeField(blank=True, null=True, verbose_name='개업일자')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='회사주소')),
                ('phone_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='전화번호')),
                ('fax_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='팩스번호')),
            ],
            options={
                'verbose_name': '회사',
                'db_table': 'company',
            },
        ),
    ]
