# Generated by Django 6.0.1 on 2026-02-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='company',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='office_phone',
        ),
        migrations.RemoveField(
            model_name='account',
            name='permission_group',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
