# Generated by Django 6.0.1 on 2026-02-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_company_remove_account_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='ACCOUNT_TABLE',
        ),
    ]
