# Generated by Django 6.0.1 on 2026-02-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(db_column='is_admin', default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
