# Generated by Django 6.0.1 on 2026-02-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, db_column='user_name', max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(db_column='account_key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(db_column='user_id', max_length=150, unique=True),
        ),
    ]
