# Generated by Django 6.0.1 on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_first_name_alter_account_id_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='account',
                    old_name='id',
                    new_name='account_key',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='account_key',
            field=models.CharField(db_column='account_key', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "account_login_history" ALTER COLUMN "account_id" TYPE varchar(50) USING "account_id"::varchar;',
            reverse_sql='ALTER TABLE "account_login_history" ALTER COLUMN "account_id" TYPE integer USING "account_id"::integer;',
        ),
    ]
