# Generated by Django 6.0.1 on 2026-02-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_key_to_char'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "ACCOUNT_TABLE_groups";',
            reverse_sql='CREATE TABLE IF NOT EXISTS "ACCOUNT_TABLE_groups" (id serial PRIMARY KEY);',
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "ACCOUNT_TABLE_user_permissions";',
            reverse_sql='CREATE TABLE IF NOT EXISTS "ACCOUNT_TABLE_user_permissions" (id serial PRIMARY KEY);',
        ),
    ]
