# Generated by Django 6.0.1 on 2026-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_remove_account_groups_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountloginhistory",
            name="agent_id",
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="accountloginhistory",
            name="client_type",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]

