# Generated by Django 5.2.7 on 2025-11-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CameraInfo",
            fields=[
                ("camera_name", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                ("ip_address", models.GenericIPAddressField(protocol="IPv4")),
                ("port", models.CharField(max_length=5)),
                ("user_name", models.CharField(blank=True, max_length=50, null=True)),
                ("password", models.CharField(blank=True, max_length=50, null=True)),
                ("rtsp_url_001", models.CharField(max_length=255)),
                (
                    "rtsp_url_002",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rtsp_url_003",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "camera_info_key",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "websocket_api",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("view_index", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "CAMERA_INFO_TABLE",
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="CAMERA_INFO_ip_addr_4af181_idx"
                    ),
                    models.Index(
                        fields=["camera_name"], name="CAMERA_INFO_camera__600187_idx"
                    ),
                    models.Index(
                        fields=["view_index"], name="CAMERA_INFO_view_in_c43b22_idx"
                    ),
                ],
            },
        ),
    ]
