# Generated by Django 5.2.7 on 2025-11-03 01:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuzzerInfoTable",
            fields=[
                (
                    "buzzer_info_key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "buzzer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "buzzer_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("buzzer_time", models.IntegerField(blank=True, null=True)),
                (
                    "buzzer_broker",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "buzzer_topic",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "BUZZER_INFO_TABLE",
                "indexes": [
                    models.Index(
                        fields=["buzzer_name"], name="BUZZER_INFO_buzzer__ffd403_idx"
                    ),
                    models.Index(
                        fields=["buzzer_location"],
                        name="BUZZER_INFO_buzzer__03f466_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BuzzerInterlockTable",
            fields=[
                (
                    "interlock_info_key",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "interlock_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("buzzer_info_key", models.CharField(max_length=50)),
                ("buzzer_name", models.CharField(blank=True, max_length=50, null=True)),
                ("camera_info_key", models.CharField(max_length=50)),
                ("camera_name", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "BUZZER_INTERLOCK_TABLE",
                "indexes": [
                    models.Index(
                        fields=["buzzer_info_key"],
                        name="BUZZER_INTE_buzzer__3a3d44_idx",
                    ),
                    models.Index(
                        fields=["camera_info_key"],
                        name="BUZZER_INTE_camera__0570c5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventInfoTable",
            fields=[
                (
                    "event_register_key",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("camera_info_key", models.CharField(max_length=50)),
                ("rtsp_url", models.CharField(max_length=200)),
                ("event_type_key", models.CharField(max_length=50)),
                (
                    "event_info_roi",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "object_to_detects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("edge_detect", models.BooleanField(default=True)),
                (
                    "event_info_roi_multi",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=200),
                            blank=True,
                            default=list,
                            size=None,
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "EVENT_INFO_TABLE",
                "indexes": [
                    models.Index(
                        fields=["camera_info_key"],
                        name="EVENT_INFO__camera__bd6ad6_idx",
                    ),
                    models.Index(
                        fields=["event_type_key"], name="EVENT_INFO__event_t_f590b2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventOccurTable",
            fields=[
                ("occur_no", models.AutoField(primary_key=True, serialize=False)),
                ("event_occur_time", models.DateTimeField()),
                (
                    "event_register_key",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("camera_info_key", models.CharField(max_length=50)),
                ("event_type_key", models.CharField(max_length=50)),
                (
                    "object_class",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "event_occur_point",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "EVENT_OCCUR_TABLE",
                "indexes": [
                    models.Index(
                        fields=["event_occur_time"],
                        name="EVENT_OCCUR_event_o_9241fb_idx",
                    ),
                    models.Index(
                        fields=["camera_info_key"],
                        name="EVENT_OCCUR_camera__d47417_idx",
                    ),
                    models.Index(
                        fields=["event_type_key"], name="EVENT_OCCUR_event_t_8eadc4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventTypeTable",
            fields=[
                (
                    "event_type_key",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("event_type_name", models.CharField(max_length=10)),
                (
                    "object_to_detects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "EVENT_TYPE_TABLE",
                "indexes": [
                    models.Index(
                        fields=["event_type_name"],
                        name="EVENT_TYPE__event_t_62b89b_idx",
                    )
                ],
            },
        ),
    ]
