# Generated by Django 5.2.7 on 2025-11-03 03:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_buzzerinfotable_buzzerinterlocktable_eventinfotable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventinfotable",
            name="event_shadow_roi",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=200),
                    blank=True,
                    default=list,
                    size=None,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
