# Generated by Codex on 2026-02-02
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models
from apps.cms.models.viewer_manage import _generate_viewer_manage_key


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_buzzerinfotable_buzzerinterlocktable_eventinfotable_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewerManage",
            fields=[
                (
                    "vever_manage_key",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        default=_generate_viewer_manage_key,
                    ),
                ),
                (
                    "camera_keys",
                    ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "setter",
                    models.ForeignKey(
                        db_column="setter_id",
                        limit_choices_to={"is_staff": True},
                        on_delete=models.deletion.CASCADE,
                        related_name="viewer_manage_setters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        limit_choices_to={"is_staff": False},
                        on_delete=models.deletion.CASCADE,
                        related_name="viewer_manage_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "VIEWER_MANAGE",
            },
        ),
        migrations.AddIndex(
            model_name="viewermanage",
            index=models.Index(fields=["setter"], name="VIEWER_MANAG_setter__f1f4a0_idx"),
        ),
        migrations.AddIndex(
            model_name="viewermanage",
            index=models.Index(fields=["user"], name="VIEWER_MANAG_user_id_14ff7d_idx"),
        ),
    ]
