# Generated by Django 6.0.1 on 2026-02-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_viewer_manage'),
        ('cms', '0005_camerainfo_is_thermal'),
    ]

    operations = [
    ]
