# Generated by Django 6.0.1 on 2026-02-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_key_to_char'),
        ('cms', '0006_merge_0003_viewer_manage_0005_camerainfo_is_thermal'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "VIEWER_MANAGE" ALTER COLUMN "setter_id" TYPE varchar(50) USING "setter_id"::varchar;',
            reverse_sql='ALTER TABLE "VIEWER_MANAGE" ALTER COLUMN "setter_id" TYPE integer USING "setter_id"::integer;',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "VIEWER_MANAGE" ALTER COLUMN "user_id" TYPE varchar(50) USING "user_id"::varchar;',
            reverse_sql='ALTER TABLE "VIEWER_MANAGE" ALTER COLUMN "user_id" TYPE integer USING "user_id"::integer;',
        ),
    ]
