# Generated by Django 6.0.1 on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_viewer_manage_account_key_type'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "VIEWER_MANAGE" RENAME COLUMN "vever_manage_key" TO "viewer_manage_key";',
            reverse_sql='ALTER TABLE "VIEWER_MANAGE" RENAME COLUMN "viewer_manage_key" TO "vever_manage_key";',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='viewermanage',
                    old_name='vever_manage_key',
                    new_name='viewer_manage_key',
                ),
            ],
        ),
        migrations.AddField(
            model_name='viewermanage',
            name='setter_key',
            field=models.CharField(blank=True, db_column='setter_key', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='viewermanage',
            name='user_key',
            field=models.CharField(blank=True, db_column='user_key', max_length=50, null=True),
        ),
        migrations.RunSQL(
            sql='UPDATE "VIEWER_MANAGE" SET setter_key = setter_id, user_key = user_id WHERE setter_key IS NULL OR user_key IS NULL;',
            reverse_sql='UPDATE "VIEWER_MANAGE" SET setter_key = NULL, user_key = NULL;',
        ),
    ]
