# Generated by Django 6.0 on 2026-02-25 09:23

import apps.cms.models.viewer_manage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_viewer_manage_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSInfoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ph_num', models.CharField(blank=True, max_length=30, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SMS_INFO',
            },
        ),
        migrations.RenameIndex(
            model_name='viewermanage',
            new_name='VIEWER_MANA_setter__0fadc0_idx',
            old_name='VIEWER_MANAG_setter__f1f4a0_idx',
        ),
        migrations.RenameIndex(
            model_name='viewermanage',
            new_name='VIEWER_MANA_user_id_f0859d_idx',
            old_name='VIEWER_MANAG_user_id_14ff7d_idx',
        ),
        migrations.AlterField(
            model_name='viewermanage',
            name='viewer_manage_key',
            field=models.CharField(db_column='viewer_manage_key', default=apps.cms.models.viewer_manage._generate_viewer_manage_key, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='smsinfotable',
            index=models.Index(fields=['user_name'], name='SMS_INFO_user_na_6f7c96_idx'),
        ),
        migrations.AddIndex(
            model_name='smsinfotable',
            index=models.Index(fields=['ph_num'], name='SMS_INFO_ph_num_6db458_idx'),
        ),
    ]
