# Generated by Django 6.0.1 on 2026-03-19 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_eventoccurtable_img_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentNode',
            fields=[
                ('agent_id', models.CharField(db_column='agent_id', max_length=128, primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=64)),
                ('account_key_last', models.CharField(blank=True, max_length=50, null=True)),
                ('client_type_last', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(blank=True, default='unknown', max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'AGENT_NODE',
            },
        ),
        migrations.CreateModel(
            name='AgentTargetState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_name', models.CharField(max_length=64)),
                ('kind', models.CharField(blank=True, default='', max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('running', models.BooleanField(blank=True, null=True)),
                ('fail_count', models.IntegerField(default=0)),
                ('restart_count', models.IntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_restart_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='target_states', to='cms.agentnode')),
            ],
            options={
                'db_table': 'AGENT_TARGET_STATE',
                'constraints': [models.UniqueConstraint(fields=('agent', 'target_name'), name='uq_agent_target_name')],
            },
        ),
    ]
